version: "3.7"

services:
  db:
    image: mysql
    container_name: mysql-contenedor
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    volumes:
      # - C:\Users\jgust\Documents\vol:/var/lib/mysql
      - /home/angel/Documentos/vol:/var/lib/mysql
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}", "--wait=5s"]
      interval: 10s
      retries: 3

  presentacion:
    image: presentacion:1.0.0
    container_name: presentacion
    ports:
      - 80:80

  servicios:
    restart: always
    image: api:1.0.0
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8000:8000
    links:
      - db
    command: python ./servicios/manage.py runserver 0.0.0.0:8000
